# Generated by Django 2.0.3 on 2018-03-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ofizioa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('8tx', 'Zortziko txikia'), ('8h', 'Zortziko handia'), ('10tx', 'Hamarreko txikia'), ('10h', 'Hamarreko handia'), ('kp', 'Kopla')], max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
