# Generated by Django 2.0.3 on 2018-03-21 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ofizioak', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofizioa',
            options={'verbose_name_plural': 'ofizioak'},
        ),
        migrations.AlterField(
            model_name='ofizioa',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ofizioa',
            name='metric',
            field=models.CharField(choices=[('zortziko txikia', 'Zortziko txikia'), ('zortziko handia', 'Zortziko handia'), ('hamarreko txikia', 'Hamarreko txikia'), ('hamarreko handia', 'Hamarreko handia'), ('kopla', 'Kopla')], max_length=20, verbose_name='Neurria'),
        ),
        migrations.AlterField(
            model_name='ofizioa',
            name='text',
            field=models.TextField(verbose_name='Testua'),
        ),
    ]
