# Generated by Django 2.0.3 on 2018-03-21 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bakarkakoa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('gaia', 'Gaia'), ('puntu-erantzuna', 'Puntu erantzuna')], max_length=20, verbose_name='Mota')),
                ('text', models.TextField(verbose_name='Testua')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'bakarkakoak',
            },
        ),
    ]
